### ISSUE TITLE
Create google collab or dockerised version of some MapReader worked examples

### ISSUE THREAD

**Issue by rwood-97** [maps-as-data/MapReader#425]
**Is your feature request related to a problem? Please describe.**
For people who want to try it out but struggle with installation, would be good to set up some notebooks on google collab.

---

Related issues:
- [ ] #437

**Comment by kallewesterling** [comment]
See #437 for a dockerised version of the worked examples.

**Comment by rwood-97** [comment]
https://github.com/maps-as-data/spatial-humanities-mapreader-workshop

**Comment by kmcdono2** [comment]
Some notes about the colab notebook:
- add mapreader somewhere in the colab notebook name?
- add warning it takes about 7 min to run the first cell (let's plan how to use this time)
- when adding context to annotations, helpful to change the patch resize (e.g. I went from 300 to 600). Otherwise it's way too small to see. Let's make a note of this?
- under "Visualise progress" the link about scores is a member-only story (not just an account, it's paid access). What else could we use instead?

**Comment by rwood-97** [comment]
- [ ] Screenshots in instructions need to be update to maps-as-data
